### ISSUE TITLE
Passing credentials into the application

### ISSUE THREAD

**Issue by philross88** [Relrin/kurier#19]
How do you pass the credentials to connect to the queue?

**Comment by Relrin** [comment]
Hello, @philross88 

Thank you for opening an issue here.

The idea is pretty straightforward: it mostly follows the [AMQP URI specification](https://www.rabbitmq.com/uri-spec.html), except the part for arguments with the "?" and the "&" symbols like in HTTP. 

So, in the application you will need to specify the URI with credentials in the `amqp://username:password@host:port/vhost` format, where:
- `username` is the used login to AMQP node
- `password` is the password, as expects
- `host` is the IP address or the shortcut to the location of the AMQP node (i.e. `localhost`)
- `port` is the port the AMQP node which is listening by the server
- `vhost` is the name of the virtual host for your AMQP node

**Comment by philross88** [comment]
Thanks but I keep getting "could not pass AMQP URL"
I am following the right syntax.

**Comment by Relrin** [comment]
In general, this application uses [URLParameters class](https://github.com/Relrin/kurier/blob/master/kurier/amqp/rpc.py#L54), which is the part of the [pika.connection module](https://github.com/pika/pika/blob/master/pika/connection.py#L661). For more details about Pika's URLs, you can also read in the official documentation, [here](https://pika.readthedocs.io/en/stable/examples/using_urlparameters.html). Make sure that you are typing the schema that requested by Pika library, in the format that the `URLParameters` class requires. 

By the way, can you provide the example of URL string, that you're using and specifying for connecting to AMQP node?

**Comment by Relrin** [comment]
Closing the issue due the long author's inactivity.
